### ISSUE TITLE
Add a contact form to the website

### ISSUE THREAD

**Issue by astersantana** [mip-master/learning_mip#4]
After a quick search on the web, I found that this might be a good option: https://just-code.team/

**Comment by astersantana** [comment]
@marcusreaiche Do you think this is something that we can do?
I have received feedback from a few people already that there should be some form of contact on the webpage.

**Comment by marcusreaiche** [comment]
Hi @astersantana, I will take a look and get back to you. I think that this would be a nice feature to add to the project.

**Comment by astersantana** [comment]
Added links to this issue page and to my LinkedIn profile. This should make it easier for people to reach out in case they have questions or comments. I will close this issue for now but eventually we should have a well-defined contact channel.
