### ISSUE TITLE
A little more theory (maybe, but maybe not)

### ISSUE THREAD

**Issue by beevabeeva** [mip-master/learning_mip#5]
Hi @astersantana and @marcusreaiche !

Thank you for putting this mini course together. I have found it to be an extremely useful and effective resource (and collation of extra resources) for getting a handle on MIP.

I spent the day going through the use cases. They are very easy to understand and follow.

In the Paper Tree exercise, I am not sure if/how this is an MIP problem. 
The flow variables are continuous and I don't see where Mr. Mip specified to `gurobipy` that some things are restricted to integers.

From what I understand, the volume of products and cost of production are all continuous (volume and money). Am I correct?

 It might (or might not) be appropriate to have a small paragraph at the end of the exercise explaining how this scenario ties back to the MIP theory. What do you think?

Some user info that might be of use to your project (to see who is using your work:P ):
- I studied basic LP and optimization in undergrad (applied maths first and second year).
- I have a postgrad degree in computer science
- I have been tasked with a MIP project (depot replenishment model in a supply chain).

**Comment by astersantana** [comment]
@beevabeeva Thank you for your comment and apologies for the very late reply!

I'm pleased to know that you found the content useful and easy to follow!

Your observation is perfectly right, the PaperTree use case, as it is, is just a linear program (LP). My goal is to extend that use case to include harvesting decisions. That's when integrality will kick in.
For now, I've added a comment in the documentation as you suggested.

If you want to chat about the replenishment problem you mentioned, feel free to reach out directly to me on LinkedIn: www.linkedin.com/in/asteroide-santana/ (at this point, Mip Master is still a small project and we don't have a well-defined channel for communication). I would be happy to coach you and share my experience on the subject.
